apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: create-order
spec:
  broker: example-broker
  filter:
    attributes:
      type: com.example.order.created
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: funqy-knative-events-codestart